<?xml version="1.0" encoding="utf-8"?><Database Name="StudentHealthCentre" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MARIA-PC\SQLEXPRESS;Initial Catalog=StudentHealthCentre;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="StudentHealthCentreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GP" Member="GP">
    <Type Name="GP">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="GP_Patient" Member="Patient" ThisKey="Id" OtherKey="GPFk" Type="Patient" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointment">
    <Type Name="Appointment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="BookingDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PatientFk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Patient_Appointment" Member="Patient" ThisKey="PatientFk" OtherKey="Id" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patient">
    <Type Name="Patient">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NhsNumber" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GPFk" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Patient_Appointment" Member="Appointment" ThisKey="Id" OtherKey="PatientFk" Type="Appointment" />
      <Association Name="GP_Patient" Member="GP" ThisKey="GPFk" OtherKey="Id" Type="GP" IsForeignKey="true" />
    </Type>
  </Table>
</Database>